import React from 'react'; import {Ionicons} from '@expo/vector-icons'; import {router,useFocusEffect} from 'expo-router'; import {SafeAreaView,ScrollView,StyleSheet,Text,View} from 'react-native'; import {theme} from '../../constants/theme'; import {getScans} from '../../services/api'; import {cleanupExpiredImageReferences} from '../../services/storage'; import {Scan} from '../../types/scan'; import MedicalDisclaimer from '../../components/safety/MedicalDisclaimer'; import {PressableScale,Reveal} from '../../components/motion'; import {Card,ExpandableText,HandMark,IconBadge,SectionTitle} from '../../components/ui';
function greeting(){const h=new Date().getHours();return h<12?'Good morning':h<18?'Good afternoon':'Good evening'}
export default function Home(){const[scans,setScans]=React.useState<Scan[]>([]);useFocusEffect(React.useCallback(()=>{cleanupExpiredImageReferences().then(getScans).then(setScans)},[]));const latest=scans[0],lead=latest?.observations[0];return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.c}>
<Reveal><View style={s.top}><View style={{flex:1}}><Text style={s.brand}>RÉVÉLA</Text><Text style={s.title}>{greeting()}</Text></View><View style={s.mark}><HandMark size={46}/></View></View></Reveal>
<Reveal index={1}><PressableScale style={s.hero} onPress={()=>router.push('/capture')} accessibilityRole="button" accessibilityLabel="Start appearance check"><View style={{flex:1}}><Text style={s.heroK}>NEW CHECK</Text><Text style={s.heroT}>Start appearance check</Text><Text style={s.heroB}>Three quick photos · about a minute</Text></View><View style={s.heroIcon}><Ionicons name="camera" size={28} color={theme.colors.espresso}/></View></PressableScale></Reveal>
<Reveal index={2}><PressableScale style={s.alt} onPress={()=>router.push('/results/intake')} accessibilityRole="button"><IconBadge name="sparkles" size={42}/><View style={{flex:1}}><Text style={s.altT}>Personalized scan</Text><Text style={s.altB}>Answer a few questions first</Text></View><Ionicons name="chevron-forward" size={20} color={theme.colors.primary}/></PressableScale></Reveal>
{latest?<>
<Reveal index={3}><SectionTitle icon="time-outline">Latest check</SectionTitle></Reveal>
<Reveal index={4}><PressableScale onPress={()=>router.push(`/scan/${latest.id}`)} accessibilityRole="button"><Card><View style={s.latestRow}><IconBadge name="scan-outline" tone="brown"/><View style={{flex:1}}><Text style={s.date}>{new Date(latest.createdAt).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</Text><Text style={s.lead}>{lead?.displayLabel??'No supported pattern above threshold'}</Text></View><Ionicons name="chevron-forward" size={20} color={theme.colors.mutedText}/></View><ExpandableText text={latest.appearanceSummary} lines={2} style={s.body}/></Card></PressableScale></Reveal>
<Reveal index={5}><View style={s.grid}><PressableScale containerStyle={{flex:1}} style={s.tile} onPress={()=>router.push('/(tabs)/progress')}><Ionicons name="images-outline" size={22} color={theme.colors.primary}/><Text style={s.tileN}>{scans.length}</Text><Text style={s.tileL}>checks saved</Text></PressableScale><PressableScale containerStyle={{flex:1}} style={[s.tile,s.tileDark]} onPress={()=>router.push('/(tabs)/routine')}><Ionicons name="water-outline" size={22} color={theme.colors.copper}/><Text style={[s.tileN,{color:theme.colors.cream}]}>{latest.morningRoutine.length+latest.eveningRoutine.length}</Text><Text style={[s.tileL,{color:theme.colors.onDarkMuted}]}>routine steps</Text></PressableScale></View></Reveal>
</>:<Reveal index={3}><Card style={s.empty}><IconBadge name="flag-outline" size={52}/><Text style={s.lead}>Start your baseline</Text><Text style={[s.body,{textAlign:'center'}]}>Three consistent checks unlock comparisons with your own baseline.</Text><View style={s.dots}>{[0,1,2].map(i=><View key={i} style={[s.dot,i<scans.length&&s.dotOn]}/>)}</View></Card></Reveal>}
<Reveal index={6}><MedicalDisclaimer compact/></Reveal>
</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.colors.background},c:{padding:20,paddingBottom:40,gap:14},top:{flexDirection:'row',alignItems:'center',marginTop:8},brand:{color:theme.colors.primary,fontWeight:'900',letterSpacing:4,fontSize:12},title:{fontSize:30,fontWeight:'900',color:theme.colors.text,marginTop:2},mark:{width:58,height:58,borderRadius:29,backgroundColor:theme.colors.espresso,alignItems:'center',justifyContent:'center'},hero:{backgroundColor:theme.colors.espresso,borderRadius:24,padding:20,flexDirection:'row',alignItems:'center',gap:14,...theme.shadow},heroK:{color:theme.colors.copper,fontWeight:'900',letterSpacing:2,fontSize:11},heroT:{color:theme.colors.cream,fontWeight:'900',fontSize:21,marginTop:4},heroB:{color:theme.colors.onDarkMuted,fontSize:13,marginTop:4},heroIcon:{width:58,height:58,borderRadius:29,backgroundColor:theme.colors.copper,alignItems:'center',justifyContent:'center'},alt:{flexDirection:'row',alignItems:'center',gap:12,borderRadius:20,padding:14,backgroundColor:theme.colors.surface,borderWidth:1,borderColor:theme.colors.border},altT:{color:theme.colors.text,fontWeight:'900',fontSize:16},altB:{color:theme.colors.mutedText,fontSize:13,marginTop:2},latestRow:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:10},date:{color:theme.colors.mutedText,fontSize:12,fontWeight:'700'},lead:{fontSize:18,fontWeight:'900',color:theme.colors.text,marginTop:2},body:{color:theme.colors.mutedText,lineHeight:21,fontSize:14},grid:{flexDirection:'row',gap:12},tile:{backgroundColor:theme.colors.surfaceAlt,borderRadius:20,padding:16,gap:2},tileDark:{backgroundColor:theme.colors.brown},tileN:{fontSize:30,fontWeight:'900',color:theme.colors.primary,marginTop:6},tileL:{color:theme.colors.mutedText,fontSize:13,fontWeight:'600'},empty:{alignItems:'center',gap:8,paddingVertical:24},dots:{flexDirection:'row',gap:8,marginTop:6},dot:{width:28,height:6,borderRadius:3,backgroundColor:theme.colors.border},dotOn:{backgroundColor:theme.colors.primary}})
