import React from 'react'; import {Ionicons} from '@expo/vector-icons'; import {useFocusEffect} from 'expo-router'; import {Keyboard,KeyboardAvoidingView,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native'; import {theme} from '../../constants/theme'; import {getJournalEntries,saveJournalEntry} from '../../services/storage'; import {JournalEntry} from '../../types/journal'; import {PressableScale,Reveal} from '../../components/motion'; import {Card,IconBadge,ScreenHeader,SectionTitle,type IconName} from '../../components/ui';
const SLEEP_LABELS:Record<JournalEntry['sleep'],string>={under_5:'<5h','5_7':'5–7h','7_9':'7–9h','9_plus':'9h+'};
function Choice({label,on,press}:{label:string;on:boolean;press:()=>void}){return <TouchableOpacity onPress={press} style={[s.choice,on&&s.on]} accessibilityRole="radio" accessibilityState={{selected:on}}><Text style={[s.choiceT,on&&s.onT]}>{label}</Text></TouchableOpacity>}
function Field({icon,label,children}:{icon:IconName;label:string;children:React.ReactNode}){return <View style={s.field}><View style={s.fieldHead}><IconBadge name={icon} size={30}/><Text style={s.head}>{label}</Text></View><View style={s.choices}>{children}</View></View>}
export default function Journal(){const[entries,setEntries]=React.useState<JournalEntry[]>([]);const[sleep,setSleep]=React.useState<JournalEntry['sleep']>('5_7');const[stress,setStress]=React.useState<JournalEntry['stress']>('medium');const[routine,setRoutine]=React.useState<JournalEntry['routineStatus']>('partial');const[notes,setNotes]=React.useState('');const[saved,setSaved]=React.useState(false);const scroll=React.useRef<ScrollView>(null);const notesY=React.useRef(0);const notesFocused=React.useRef(false);React.useEffect(()=>{const sub=Keyboard.addListener('keyboardDidShow',()=>{if(notesFocused.current)scroll.current?.scrollTo({y:Math.max(0,notesY.current-12),animated:true})});return()=>sub.remove()},[]);useFocusEffect(React.useCallback(()=>{getJournalEntries().then(setEntries)},[]));async function save(){const x={id:`journal_${Date.now()}`,createdAt:new Date().toISOString(),sleep,stress,routineStatus:routine,newProduct:false,notes};await saveJournalEntry(x);setEntries([x,...entries]);setNotes('');setSaved(true)}return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.safe} behavior="padding"><ScrollView ref={scroll} contentContainerStyle={s.c} keyboardShouldPersistTaps="handled">
<Reveal><ScreenHeader kicker="Context" title="Journal" icon="book" subtitle="Optional notes for your timeline. Révéla may show associations, never causes."/></Reveal>
<Reveal index={1}><Card style={s.form}>
<Field icon="moon-outline" label="Sleep">{(Object.entries(SLEEP_LABELS) as Array<[JournalEntry['sleep'],string]>).map(([v,l])=><Choice key={v} label={l} on={sleep===v} press={()=>{setSaved(false);setSleep(v)}}/>)}</Field>
<Field icon="pulse-outline" label="Stress">{(['low','medium','high'] as const).map(v=><Choice key={v} label={v} on={stress===v} press={()=>{setSaved(false);setStress(v)}}/>)}</Field>
<Field icon="checkmark-done-outline" label="Routine">{(['complete','partial','missed'] as const).map(v=><Choice key={v} label={v} on={routine===v} press={()=>{setSaved(false);setRoutine(v)}}/>)}</Field>
</Card></Reveal>
<View onLayout={e=>{notesY.current=e.nativeEvent.layout.y}}><Reveal index={2}><View style={s.fieldHead}><IconBadge name="create-outline" size={30}/><Text style={s.head}>Notes</Text></View><TextInput onFocus={()=>{notesFocused.current=true}} onBlur={()=>{notesFocused.current=false}} multiline value={notes} onChangeText={t=>{setSaved(false);setNotes(t)}} placeholder="Anything worth remembering today?" placeholderTextColor={theme.colors.mutedText} style={s.input}/></Reveal></View>
<Reveal index={3}><PressableScale style={[s.btn,saved&&s.btnSaved]} onPress={save} accessibilityRole="button"><Ionicons name={saved?'checkmark-done':'bookmark-outline'} size={18} color={theme.colors.cream}/><Text style={s.bt}>{saved?'Entry saved':'Save journal entry'}</Text></PressableScale></Reveal>
{entries.length?<Reveal index={4}><SectionTitle icon="albums-outline">Recent entries</SectionTitle></Reveal>:null}
{entries.slice(0,5).map((x,i)=><Reveal key={x.id} index={5+i}><Card style={s.entry}><Text style={s.date}>{new Date(x.createdAt).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</Text><View style={s.tags}><Tag icon="moon-outline" text={SLEEP_LABELS[x.sleep]??x.sleep}/><Tag icon="pulse-outline" text={x.stress}/><Tag icon="checkmark-done-outline" text={x.routineStatus}/></View>{x.notes?<Text style={s.note} numberOfLines={3}>{x.notes}</Text>:null}</Card></Reveal>)}
</ScrollView></KeyboardAvoidingView></SafeAreaView>}
function Tag({icon,text}:{icon:IconName;text:string}){return <View style={s.tag}><Ionicons name={icon} size={13} color={theme.colors.brown}/><Text style={s.tagT}>{text}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.colors.background},c:{padding:20,paddingBottom:40,gap:14},form:{gap:16},field:{gap:10},fieldHead:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:8},head:{fontSize:16,fontWeight:'900',color:theme.colors.text},choices:{flexDirection:'row',flexWrap:'wrap',gap:8},choice:{paddingHorizontal:14,paddingVertical:9,borderRadius:99,borderWidth:1,borderColor:theme.colors.border,backgroundColor:theme.colors.background},on:{backgroundColor:theme.colors.primary,borderColor:theme.colors.primary},choiceT:{color:theme.colors.text,textTransform:'capitalize'},onT:{color:theme.colors.cream,fontWeight:'900'},input:{minHeight:90,textAlignVertical:'top',backgroundColor:theme.colors.surface,borderWidth:1,borderColor:theme.colors.border,borderRadius:16,padding:14,color:theme.colors.text},btn:{backgroundColor:theme.colors.primary,borderRadius:16,padding:15,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},btnSaved:{backgroundColor:theme.colors.brown},bt:{color:theme.colors.cream,fontWeight:'900'},entry:{padding:14,gap:8},date:{fontWeight:'900',color:theme.colors.text},tags:{flexDirection:'row',flexWrap:'wrap',gap:6},tag:{flexDirection:'row',alignItems:'center',gap:4,backgroundColor:theme.colors.surfaceAlt,borderRadius:99,paddingHorizontal:9,paddingVertical:4},tagT:{color:theme.colors.brown,fontSize:12,fontWeight:'700',textTransform:'capitalize'},note:{color:theme.colors.text,lineHeight:20}})
