import React from 'react'; import {Ionicons} from '@expo/vector-icons'; import {router,useFocusEffect} from 'expo-router'; import {SafeAreaView,ScrollView,StyleSheet,Text,View} from 'react-native'; import {theme} from '../../constants/theme'; import {getScans} from '../../services/api'; import {Scan} from '../../types/scan'; import {buildBaseline,compareToBaseline,MIN_BASELINE_SCANS} from '../../services/baseline'; import {PressableScale,Reveal} from '../../components/motion'; import {Card,IconBadge,ScreenHeader,SectionTitle,type IconName} from '../../components/ui';
const labels:any={acne_like:'Acne-like appearance',dryness_like:'Dryness-like appearance',oiliness_like:'Oiliness-like appearance',dark_circle_like:'Dark-circle appearance',hyperpigmentation_like:'Uneven-pigmentation-like appearance'};
const icons:Record<string,IconName>={acne_like:'ellipse-outline',dryness_like:'leaf-outline',oiliness_like:'water-outline',dark_circle_like:'eye-outline',hyperpigmentation_like:'color-palette-outline'};
export default function Progress(){const[scans,setScans]=React.useState<Scan[]>([]);useFocusEffect(React.useCallback(()=>{getScans().then(setScans)},[]));const base=buildBaseline(scans.slice(1));const changes=scans[0]&&base?compareToBaseline(scans[0],base):[];return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.c}>
<Reveal><ScreenHeader kicker="Personal history" title="Progress" icon="stats-chart" subtitle="Compared with your own past checks — never a medical standard."/></Reveal>
{!base?<Reveal index={1}><Card style={s.center}><IconBadge name="hourglass-outline" size={52}/><Text style={s.head}>Building your baseline</Text><View style={s.dots}>{Array.from({length:MIN_BASELINE_SCANS},(_,i)=><View key={i} style={[s.dot,i<scans.length&&s.dotOn]}/>)}</View><Text style={[s.body,{textAlign:'center'}]}>{Math.min(scans.length,MIN_BASELINE_SCANS)} of {MIN_BASELINE_SCANS} checks. Same lighting and angle each time helps.</Text></Card></Reveal>:<Reveal index={1}><Card><Text style={s.head}>Since your baseline</Text>{changes.map(x=>{const pct=Math.round(x.delta*100);const stable=Math.abs(pct)<=2;return <View key={x.characteristic} style={s.row}><IconBadge name={icons[x.characteristic]??'ellipse-outline'} size={34} tone="brown"/><Text style={s.rowL}>{labels[x.characteristic]}</Text><View style={[s.pill,{backgroundColor:stable?theme.colors.surfaceAlt:theme.colors.primarySoft}]}><Text style={[s.pillT,{color:stable?theme.colors.brown:theme.colors.primary}]}>{stable?'Stable':`${pct>0?'↑':'↓'} ${Math.abs(pct)} pts`}</Text></View></View>})}<Text style={s.note}>Differences in model confidence, not medical severity.</Text></Card></Reveal>}
<Reveal index={2}><SectionTitle icon="calendar-outline">Check history</SectionTitle></Reveal>
{scans.length===0?<Reveal index={3}><Text style={s.body}>Your checks will appear here.</Text></Reveal>:null}
{scans.map((x,i)=><Reveal key={x.id} index={3+i}><PressableScale style={s.item} onPress={()=>router.push(`/scan/${x.id}`)} accessibilityRole="button"><View style={s.dateBox}><Text style={s.dateDay}>{new Date(x.createdAt).getDate()}</Text><Text style={s.dateMon}>{new Date(x.createdAt).toLocaleDateString(undefined,{month:'short'})}</Text></View><Text style={s.itemT} numberOfLines={2}>{x.observations[0]?.displayLabel??'No supported pattern above threshold'}</Text><Ionicons name="chevron-forward" size={20} color={theme.colors.primary}/></PressableScale></Reveal>)}
</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.colors.background},c:{padding:20,paddingBottom:40,gap:12},center:{alignItems:'center',gap:10,paddingVertical:22},head:{fontSize:18,fontWeight:'900',color:theme.colors.text,marginBottom:4},body:{color:theme.colors.mutedText,lineHeight:20},dots:{flexDirection:'row',gap:8},dot:{width:28,height:6,borderRadius:3,backgroundColor:theme.colors.border},dotOn:{backgroundColor:theme.colors.primary},row:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:10,borderBottomWidth:1,borderBottomColor:theme.colors.border},rowL:{flex:1,color:theme.colors.text,fontWeight:'600'},pill:{borderRadius:99,paddingHorizontal:10,paddingVertical:5},pillT:{fontWeight:'900',fontSize:12},note:{fontSize:11,color:theme.colors.mutedText,lineHeight:17,marginTop:12},item:{backgroundColor:theme.colors.surface,borderRadius:18,borderWidth:1,borderColor:theme.colors.border,padding:12,flexDirection:'row',alignItems:'center',gap:12},dateBox:{width:50,height:50,borderRadius:14,backgroundColor:theme.colors.espresso,alignItems:'center',justifyContent:'center'},dateDay:{color:theme.colors.cream,fontWeight:'900',fontSize:18},dateMon:{color:theme.colors.copper,fontWeight:'800',fontSize:11,textTransform:'uppercase'},itemT:{flex:1,fontWeight:'800',color:theme.colors.text}})
