import React from 'react'; import {Ionicons} from '@expo/vector-icons'; import {useFocusEffect} from 'expo-router'; import {Animated,SafeAreaView,ScrollView,StyleSheet,Text,TouchableOpacity,View} from 'react-native'; import {theme} from '../../constants/theme'; import {getScans} from '../../services/api'; import {saveRoutineLog} from '../../services/storage'; import {Scan} from '../../types/scan'; import MedicalDisclaimer from '../../components/safety/MedicalDisclaimer'; import {PressableScale,Reveal} from '../../components/motion'; import {Card,IconBadge,ScreenHeader} from '../../components/ui';
function Check({on}:{on:boolean}){const v=React.useRef(new Animated.Value(on?1:0)).current;React.useEffect(()=>{Animated.spring(v,{toValue:on?1:0,useNativeDriver:true,friction:4,tension:160}).start()},[on,v]);return <View style={[s.box,on&&s.checked]}><Animated.View style={{transform:[{scale:v}]}}><Ionicons name="checkmark" size={16} color={theme.colors.cream}/></Animated.View></View>}
export default function Routine(){const[scan,setScan]=React.useState<Scan>();const[done,setDone]=React.useState<string[]>([]);const[saved,setSaved]=React.useState(false);useFocusEffect(React.useCallback(()=>{getScans().then(x=>setScan(x[0]))},[]));if(!scan)return <SafeAreaView style={s.safe}><View style={s.c}><Reveal><ScreenHeader kicker="Personal care" title="Routine" icon="checkmark-circle"/></Reveal><Reveal index={1}><Card style={s.empty}><IconBadge name="sunny-outline" size={52}/><Text style={s.body}>Complete an appearance check to build a simple routine.</Text></Card></Reveal></View></SafeAreaView>;const steps=[...scan.morningRoutine.map(x=>['morning',x] as const),...scan.eveningRoutine.map(x=>['evening',x] as const)];const pct=steps.length?done.length/steps.length:0;function toggle(x:string){setSaved(false);setDone(a=>a.includes(x)?a.filter(y=>y!==x):[...a,x])}async function save(){for(const period of ['morning','evening'] as const){const all=steps.filter(x=>x[0]===period).map(x=>x[1]);await saveRoutineLog({id:`${new Date().toISOString().slice(0,10)}_${period}`,date:new Date().toISOString(),period,completed:done.filter(x=>all.includes(x)),total:all.length})}setSaved(true)}return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.c}>
<Reveal><ScreenHeader kicker="Personal care" title="Today's routine" icon="checkmark-circle"/></Reveal>
<Reveal index={1}><View style={s.meter}><View><Text style={s.meterN}>{done.length} of {steps.length}</Text><Text style={s.meterL}>steps done today</Text></View><View style={s.track}><View style={[s.fill,{width:`${Math.round(pct*100)}%`}]}/></View></View></Reveal>
{(['morning','evening'] as const).map((period,pi)=><Reveal key={period} index={2+pi}><View style={s.periodRow}><IconBadge name={period==='morning'?'sunny':'moon'} size={32} tone={period==='morning'?'ginger':'espresso'}/><Text style={s.head}>{period==='morning'?'Morning':'Evening'}</Text></View><Card style={s.card}>{steps.filter(x=>x[0]===period).map(([,x])=><TouchableOpacity key={x} style={s.row} onPress={()=>toggle(x)} accessibilityRole="checkbox" accessibilityState={{checked:done.includes(x)}}><Check on={done.includes(x)}/><Text style={[s.step,done.includes(x)&&s.stepDone]}>{x}</Text></TouchableOpacity>)}</Card></Reveal>)}
<Reveal index={4}><PressableScale style={[s.btn,saved&&s.btnSaved]} onPress={save} accessibilityRole="button"><Ionicons name={saved?'checkmark-done':'save-outline'} size={18} color={theme.colors.cream}/><Text style={s.bt}>{saved?'Saved for today':"Save today's progress"}</Text></PressableScale></Reveal>
<Reveal index={5}><MedicalDisclaimer compact/></Reveal>
</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.colors.background},c:{padding:20,paddingBottom:40,gap:12},body:{color:theme.colors.mutedText,lineHeight:21,textAlign:'center'},empty:{alignItems:'center',gap:12,paddingVertical:24},meter:{backgroundColor:theme.colors.espresso,borderRadius:22,padding:18,gap:12},meterN:{color:theme.colors.cream,fontSize:24,fontWeight:'900'},meterL:{color:theme.colors.onDarkMuted,fontSize:13},track:{height:8,borderRadius:99,backgroundColor:'rgba(255,250,242,0.15)',overflow:'hidden'},fill:{height:8,borderRadius:99,backgroundColor:theme.colors.copper},periodRow:{flexDirection:'row',alignItems:'center',gap:10,marginTop:6,marginBottom:8},head:{fontSize:18,fontWeight:'900',color:theme.colors.text},card:{padding:6},row:{flexDirection:'row',alignItems:'center',gap:12,padding:11},box:{width:26,height:26,borderRadius:8,borderWidth:2,borderColor:theme.colors.border,alignItems:'center',justifyContent:'center'},checked:{backgroundColor:theme.colors.brown,borderColor:theme.colors.brown},step:{fontSize:15,color:theme.colors.text,flex:1},stepDone:{color:theme.colors.mutedText,textDecorationLine:'line-through'},btn:{backgroundColor:theme.colors.primary,borderRadius:16,padding:15,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},btnSaved:{backgroundColor:theme.colors.brown},bt:{color:theme.colors.cream,fontWeight:'900'}})
