import React from 'react'; import {Ionicons} from '@expo/vector-icons'; import {router,useLocalSearchParams} from 'expo-router'; import {ActivityIndicator,SafeAreaView,ScrollView,StyleSheet,Text,TouchableOpacity,View} from 'react-native'; import {theme} from '../../constants/theme'; import {getScanById} from '../../services/api'; import {Scan} from '../../types/scan'; import MedicalDisclaimer from '../../components/safety/MedicalDisclaimer'; import ObservationCard from '../../components/scan/ObservationCard'; import {Reveal} from '../../components/motion'; import {Card,ExpandableText,ScreenHeader,SectionTitle} from '../../components/ui'; import {HomeButton} from '../../src/components/HomeButton';
export default function Detail(){const{id}=useLocalSearchParams<{id:string}>();const[scan,setScan]=React.useState<Scan>();React.useEffect(()=>{getScanById(id).then(setScan)},[id]);if(!scan)return <SafeAreaView style={s.safe}><View style={s.top}><HomeButton/></View><View style={s.center}><ActivityIndicator color={theme.colors.primary}/><Text style={s.body}>Loading check…</Text></View></SafeAreaView>;return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.c}>
<View style={s.nav}><TouchableOpacity onPress={()=>router.back()} style={s.back} accessibilityRole="button" accessibilityLabel="Back"><Ionicons name="arrow-back" size={18} color={theme.colors.primary}/><Text style={s.backT}>Back</Text></TouchableOpacity><HomeButton iconOnly/></View>
<Reveal><ScreenHeader kicker={new Date(scan.createdAt).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})} title="Appearance check" icon="scan-outline"/></Reveal>
<Reveal index={1}><SectionTitle icon="eye-outline">Visible characteristics</SectionTitle></Reveal>
{scan.observations.map((x,i)=><Reveal key={x.characteristic} index={2+i}><ObservationCard observation={x}/></Reveal>)}
<Reveal index={3}><SectionTitle icon="document-text-outline">Summary</SectionTitle><Card><ExpandableText text={scan.appearanceSummary} lines={4} style={s.body}/></Card></Reveal>
<Reveal index={4}><SectionTitle icon="camera-outline">Capture information</SectionTitle><Card><Text style={s.body}>{scan.quality.note}</Text><Text style={s.note}>Analysis purpose: cosmetic tracking · Disclaimer: {scan.disclaimerVersion}</Text></Card></Reveal>
<Reveal index={5}><MedicalDisclaimer compact/></Reveal>
</ScrollView></SafeAreaView>}
const s=StyleSheet.create({nav:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},top:{paddingHorizontal:20,paddingTop:28},safe:{flex:1,backgroundColor:theme.colors.background},c:{padding:20,paddingBottom:40,gap:10},center:{flex:1,justifyContent:'center',alignItems:'center',gap:10},back:{flexDirection:'row',alignItems:'center',gap:6,marginTop:8,marginBottom:6,alignSelf:'flex-start'},backT:{color:theme.colors.primary,fontWeight:'900'},body:{color:theme.colors.mutedText,lineHeight:21},note:{fontSize:11,color:theme.colors.mutedText,marginTop:10}})
